import type { NextPage } from "next";
import Head from "next/head";
import { Hero } from "../ui/Hero";
import { Navbar } from "../ui/Navbar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>MMO.sg Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Hero />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
