import type {GetServerSideProps, NextPage} from "next";
import Head from "next/head";
import {Hero} from "../ui/Hero";
import {Navbar} from "../ui/Navbar";
import {getUser} from "@supabase/auth-helpers-nextjs";
import {useUser} from "@supabase/auth-helpers-react";
import {useRouter} from "next/router";
import {useEffect} from "react";
import {setCookie} from "cookies-next";
import {COOKIE_KEY_USER_ID} from "../configs/cookie";

const Home: NextPage = () => {
  const {user} = useUser()
  const router = useRouter()

  useEffect(() => {
    if (user) {
      const {email} = user
      setCookie(COOKIE_KEY_USER_ID, email)
      router.push("/dashboard")
    }

  }, [user, router])

  return (
    <div>
      <Head>
        <title>MMO.sg Dashboard</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main>
        <Navbar/>
        <Hero/>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const {user} = await getUser(context)
  if (user) {
    return {
      redirect: {
        destination: '/dashboard',
        permanent: false,
      },
    }
  }

  return {
    props: {}
  }
}
